# Generated by Django 5.1.5 on 2025-08-09 15:39

import django.db.models.deletion
import employees.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('employee_name', models.CharField(max_length=50)),
                ('years_of_experience', models.IntegerField(blank=True, null=True)),
                ('phone_number', models.CharField(max_length=15, validators=[employees.validators.validate_phone_number])),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('job_level', models.CharField(choices=[('Junior', 'Junior'), ('Senior', 'Senior'), ('Project Manager', 'Project Manager'), ('Team Leader', 'Team Leader')], max_length=100)),
                ('about_employee', models.TextField(blank=True, null=True)),
                ('projects', models.ManyToManyField(blank=True, related_name='employees', to='projects.project')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
