# Generated by Django 5.1.5 on 2025-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='employee_picture',
            field=models.ImageField(blank=True, null=True, upload_to='employees/'),
        ),
    ]
