# Generated by Django 5.1.5 on 2025-05-04 21:02

import django.db.models.deletion
import finalProject.professionals.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, validators=[finalProject.professionals.validators.validate_phone_number])),
                ('occupation', models.CharField(choices=[('Engineer', 'Engineer'), ('Architect', 'Architect')], max_length=100)),
                ('age', models.IntegerField()),
                ('number_of_projects', models.IntegerField()),
                ('about_me', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('expenses', models.FloatField()),
                ('description', models.TextField()),
                ('professional', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='professionals.professional')),
            ],
        ),
    ]
