# Generated by Django 5.1.5 on 2025-05-18 20:17

import django.db.models.deletion
import finalProject.professionals.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Professional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('personal_photo', models.URLField()),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone_number', models.CharField(max_length=11, validators=[finalProject.professionals.validators.validate_phone_number])),
                ('occupation', models.CharField(choices=[('Engineer', 'Engineer'), ('Architect', 'Architect')], max_length=100)),
                ('age', models.IntegerField()),
                ('number_of_projects', models.IntegerField()),
                ('about_me', models.TextField(blank=True, null=True)),
                ('slug', models.SlugField(blank=True, editable=False, null=True, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
