# Generated by Django 5.1.5 on 2025-05-09 14:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professional',
            old_name='first_name',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='professional',
            name='last_name',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
