# Generated by Django 5.1.5 on 2025-05-25 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_profile_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='number_of_projects',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
