# Generated by Django 5.1.5 on 2025-05-26 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_profile_number_of_projects'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='number_of_projects',
        ),
    ]
