# Generated by Django 5.1.5 on 2025-05-26 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_project_project_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='expenses',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
