# Generated by Django 5.1.5 on 2025-05-26 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_alter_project_expenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
