# Generated by Django 5.1.5 on 2025-09-21 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project_pictures', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectpicture',
            name='picture',
            field=models.ImageField(upload_to='projects_photos/'),
        ),
    ]
